name:                open-u-tex
version:             0.1.0.0
github:              githubuser/open-u-tex
license:             BSD3
author:              Kenny Shen
maintainer:          kenny@machinesung.com
copyright:           2017 Kenny Shen

extra-source-files:
- README.md

synopsis:            Generate a TeX template for Open University assignments
description:         Please see the README on Github at <https://github.com/qoelet/open-u-tex#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - dhall
  - getopt-generics
  - interpolate
  - string-conversions
  - text

library:
  source-dirs: src
  exposed-modules:
    - TeX

executables:
  open-u-tex:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-u-tex

tests:
  open-u-tex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-u-tex
    - hspec
